@startuml

actor User as U
actor Operator as O

rectangle "Payment system" {
    usecase "Certification\nauthority" as CA #lawngreen
    usecase "Processing\nCenter" as proc #lawngreen
    usecase "Authentication" as proca #yellow

    proca <-[#lawngreen]> proc
    proc <.[#lawngreen]> CA
}

rectangle "POS Terminal" {
    usecase "Communication\n(CM)" as comm #red
    usecase "Screen\n(SS)" as screen #red
    usecase "NFC\n(MS)" as nfc #red
    usecase "Card-reader\n(MS)" as card #red

    usecase "Response\nverification\n(SM)" as ver #yellow
    usecase "ID provider\n(ML)" as idp #yellow
    usecase "Risk management\n(CM)" as rm #lawngreen

    usecase "Printer\n(SS)" as printer #lawngreen
    usecase "Keyboard\n(SS)" as kb #lawngreen
    usecase "Authentication\n(MM)" as auth #lawngreen
    usecase "Transaction\ndata storage\n(SS)" as tds #lawngreen
}

CA .[#lawngreen].> ver
CA .[#lawngreen].> idp

U ...[#red]> nfc
U ..[#red]> card
U ..[#red]> kb
O .[#lawngreen]> kb

nfc  --[#red]> idp
nfc  <--[#lawngreen] idp
card --[#red]> idp
card <--[#lawngreen] idp

kb -[#lawngreen]-> tds : Amount
kb --[#lawngreen]-> rm : PIN

tds --[#lawngreen]> rm
idp --[#lawngreen]> rm
idp <--[#lawngreen] rm

tds --[#lawngreen]> auth
rm -[#lawngreen]> auth
auth --[#lawngreen]> comm
ver --[#lawngreen]> auth

proca <--[#red]- comm
proca --[#lawngreen]-> comm
comm --[#red]-> ver
ver --[#lawngreen]> printer
ver --[#lawngreen]> screen

legend right
| Цвет          | Тип                               |#| Обозначение | Сложность|# |Обозначение | Объем |
| <#lawngreen>  | Доверенный компонент              |#| S | Simple  |#| S|Small|
| <#red>        | Недоверенный компонент            |#| M | Medium  |#| M|Medium|
| <#yellow>     | Компонент повышающий целостность  |#| C | Complex |#| L|Large|
end legend

@enduml