@startuml
title "Негативный сценарий 2. Принтер\nНарушение ЦБ№3"

autonumber

actor "Покупатель" as client
actor "Оператор" as seller
participant "Клавиатура" as kb
participant "Центральная\nсистема\nуправления" as sys
participant "Экран" as screen
participant "Связь" as conn
'participant "Контроль\nАКБ" as batt
participant "NFC чип" as nfc
participant "Принтер" as printer #red
'participant "Карт-ридер" as card
participant "Процессинговый\nцентр" as proc

note over sys
терминал уже включён и готов к работе
end note

group Инициация транзакции
seller -> kb: ввод информации
kb -> sys++: новая транзакция
sys -> screen: старт авторизации транзакции
screen -> seller: старт авторизации транзакции
seller -> client: старт авторизации
end
group Авторизация транзакции
client -> nfc++: карта/гаджет
nfc -> sys--: id клиента
sys -> conn++: запрос авторизации транзакции
conn -> proc++: запрос авторизации транзакции
proc -> proc: контроль транзакции
note over proc #orange
транзакция отменена
end note
proc --> conn--: транзакция не авторизована
conn --> sys--: транзакция не авторизована
sys -> screen--: транзакция не авторизована
screen -> seller:  транзакция не авторизована
end
group Финализация транзакции
seller -> kb: печать квитанции
kb -> sys: печать квитанции
sys -> printer--: печать квитанции
activate printer #red
note over printer #red
Подмена статуса при печати
end note
printer -> client--: квитанция
seller -[#red]> client: товар
note over seller #red
товар не оплачен, но выдан
end note
end
@enduml